name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Run Prettier check once (on Node 20.x) to fail CI if files are unformatted
      - name: Check formatting
        if: matrix.node-version == '20.x'
        run: npm run format

      - name: Compile TypeScript
        run: npm run compile

      - name: Run unit tests
        run: npm test
