name: Publish Extension

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Test
        run: npm test

      - name: Verify tag matches package.json version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PKG_VERSION="$(node -p "require('./package.json').version")"
          echo "Tag: $TAG"
          echo "package.json version: $PKG_VERSION"
          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "::error ::Tag ($TAG) must equal <package.json version> ($PKG_VERSION)"
            exit 1
          fi

      - name: Package VSIX (artifact for download)
        run: npx vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: tap-outline-${{ github.ref_name }}
          path: '*.vsix'

      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish
